Set particle set count to the correct value
mayfieldrobotics/navigation pull request #43
Opened 2017-08-11 00:50 UTC by Boberito25

2017-08-14 17:57 UTC, KaijenHsiao commented on amcl/src/amcl/pf/pf.c
>    num_samples_per_particle =set->sample_count/num_guesses;
Where does set->sample_count get set in the first place (since you're using it here)?

2017-08-14 18:56 UTC, Boberito25 commented on amcl/src/amcl/pf/pf.c
>    num_samples_per_particle =set->sample_count/num_guesses;
Ah made a mistake there. It gets set here

2017-08-14 18:57 UTC, Boberito25 commented
@KaijenHsiao issue should be resolved

2017-08-14 20:40 UTC, haidai requested changes
Logic doesn't make sense.

2017-08-14 20:40 UTC, haidai commented on amcl/src/amcl/pf/pf.c
> +  set->sample_count = num_samples_per_particle * num_guesses;
I don't understand how this works out. `num_guesses` cancels out and the expression evaluates to the expression that it replaces:
```
set->sample_count = pf->max_samples;
```

2017-08-14 20:40 UTC, haidai commented on amcl/src/amcl/pf/pf.c
> +  if(set->sample_count > pf->max_samples)
And if that's the case, then this conditional would never evaluate to true.

2017-08-14 22:16 UTC, Boberito25 commented on amcl/src/amcl/pf/pf.c
> +  if(set->sample_count > pf->max_samples)
Ya your right that cant happen so dont need that block.

2017-08-14 22:17 UTC, Boberito25 commented on amcl/src/amcl/pf/pf.c
> +  set->sample_count = num_samples_per_particle * num_guesses;
num_guesses doesnt cancel out because of integer division

2017-08-16 20:49 UTC, haidai commented on amcl/src/amcl/pf/pf.c
> +  if (num_samples_per_particle == 0)
What? It just fails without any error messages or return values? It can at least create a sample for each guess up until `pf->max_samples` and issue a warning, or even sample up until `num_guesses` (and warn).

2017-08-17 07:48 UTC, Boberito25 commented on amcl/src/amcl/pf/pf.c
> +  if (num_samples_per_particle == 0)
Ya gonna change this. Put that in as a place holder until I could talk to either you or kaijen.  Will take the first n hypotheses where n is pf->max_samples

2017-08-28 20:44 UTC, haidai approved these changes

2017-08-28 20:45 UTC, merged